### ISSUE TITLE
怎么获取vcard 的联系人信息

### ISSUE THREAD

**Issue by ThirdPrince** [Dboy233/ShareToMe#1]
求指导

**Comment by Dboy233** [comment]
> 求指导

你是说app接受到Vcard的分享信息吗

**Comment by Dboy233** [comment]
> 求指导
# manifest 需要在activity中设置过滤条件，设置接收分享Vcard的事件。
![image](https://user-images.githubusercontent.com/37604230/103389353-51ae3800-4b49-11eb-8a59-260901ad2c45.png)

**Comment by ThirdPrince** [comment]
分享信息是拿的到的，但是像微信那种 vcard 分享过来的是联系人的name 命名的文件，这怎么做到呢

**Comment by Dboy233** [comment]
> 分享信息是拿的到的，但是像微信那种 vcard 分享过来的是联系人的name 命名的文件，这怎么做到呢

我觉得应该是这样实现的，new一个File将Vcard的信息，生成一个新的文件命名文件格式为vcf保存到本地，然后通过聊天发送给好友就可以了。

**Comment by Dboy233** [comment]
> 分享信息是拿的到的，但是像微信那种 vcard 分享过来的是联系人的name 命名的文件，这怎么做到呢

看了一下vcf的文件格式，其实就是个文本，将获取的Vcard信息toString就行了。

**Comment by Dboy233** [comment]
> > 分享信息是拿的到的，但是像微信那种 vcard 分享过来的是联系人的name 命名的文件，这怎么做到呢
> 
> 看了一下vcf的文件格式，其实就是个文本，将获取的Vcard信息toString就行了。

既然有这个需求，我周末更新一下，把这个功能也集成进去。

**Comment by ThirdPrince** [comment]
谢啦

**Comment by Dboy233** [comment]
已经搞定了，看demo的使用方式
